### ISSUE TITLE
Error: Cannot find module 'elementtree'

### ISSUE THREAD

**Issue by oak-tree** [dpa99c/cordova-custom-config#11]
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: co.centure.mobile
        Name: CNATURE
        Activity: MainActivity
        Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.0
Error: Cannot find module 'elementtree'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\oak\git\centure\centure-app\beethoven\plugin                                                           s\cordova-custom-config\hooks\fileUtils.js:7:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by oak-tree** [comment]
tried  to fix by installing global   'elementtree' via npm but still the same problem

**Comment by oak-tree** [comment]
i fixed by by linking elementtree and tostr to plugin path. but it does seem like configuration the plugin can handle

**Comment by oak-tree** [comment]
now i see that `dep` are inside package.json.` for some reason `cordova plugin add` does not run `npm install`

**Comment by ZiFFeL1992** [comment]
Facing this as well on 3.x.

What info do you need to help you solve it?

**Comment by dpa99c** [comment]
@ZiFFeL1992 Please update to v3.0.8 (remove and re-add plugin). I have fixed several bugs in 3.0.x which should solve your problem

**Comment by ZiFFeL1992** [comment]
Will do it, thanks!

**Comment by CorentinPacaud** [comment]
I am facing this issue again.
I'm running on npm 4.6.1.
Error loading dependencies (Cannot find module 'elementtree') - attempting to resolve

**Comment by Muzietto** [comment]
This `elementtree` module is still giving trouble. See https://github.com/dpa99c/cordova-custom-config/issues/149
