### ISSUE TITLE
[Bug][Android] '"{{proj_path}}\platforms\android\cordova\version"' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ebhsgit** [dpa99c/cordova-custom-config#170]
# Bug report

**Current behavior:**

Running `cordova prepare android` fails with the following error

```
cordova-custom-config: Skipping auto-restore of config file backup(s)
Error: Command failed: "{{proj_path}}\platforms\android\cordova\version"
'"{{proj_path}}\platforms\android\cordova\version"' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"{{proj_path}}\\platforms\\android\\cordova\\version"'
}
[ERROR] An error occurred while running subprocess cordova.
```

Project was compiling fine before adding this plugin.
Then added plugin via: `cordova plugin add cordova-custom-config`
No changes to any files (other than `package.json and `package-lock.json` from adding the plugin)
Then run `cordova prepare android`. And gets the error

The issue seems to be a conflict with `cordova-plugin-add-swift-support`

If I remove `cordova-plugin-add-swift-support`, this plugin works.

**Expected behavior:**

The project should compile

**Steps to reproduce:**

Test project that shows this issue

https://github.com/ebhsgit/custom-config-test

Check out test project and run `cordova android prepare`

**Screenshots**

**Environment information**

- Cordova CLI version
	- `10.0.0`
- Cordova platform version
	```
Installed platforms:
  android 10.1.1
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  windows ^7.0.0
```

- Plugins & versions installed in project (including this plugin)
    ```
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

- Dev machine OS and version, e.g.
    - Windows 10
        - `20H2`
	
_Android build issue:_	
- Node JS version
    - `v12.19.0`
- Gradle version
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27/11/2021   1:40 PM                6.6.1
d-----        27/11/2021   1:40 PM                7.1.1
d-----        27/11/2021   1:40 PM                buildOutputCleanup
d-----        27/11/2021   1:40 PM                checksums
d-----        27/11/2021   1:40 PM                configuration-cache
d-----        27/11/2021   1:40 PM                vcs-1
```

- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

https://github.com/ebhsgit/custom-config-test

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by ebhsgit** [comment]
Not an issue with plugin

Issue is in `cordova-plugin-add-swift-support`
