### ISSUE TITLE
Installing plugin fails

### ISSUE THREAD

**Issue by henritoivar** [dpa99c/cordova-custom-config#38]
C:\dev\code\tippy-app>cordova plugin add cordova-custom-config
Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" for android
cordova-custom-config: Installing plugin dependencies...
Running command: "C:\Program Files\nodejs\node.exe" C:\dev\code\tippy-app\hooks\after_plugin_add\010_register_plugin.js C:\dev\code\tippy-app
Running command: "C:\Program Files\nodejs\node.exe" C:\dev\code\tippy-app\hooks\after_plugin_add\register_plugins.js C:\dev\code\tippy-app
C:\dev\code\tippy-app\hooks\after_plugin_add\register_plugins.js:12
  if (! _.contains(packageJSON.cordovaPlugins, plugin)) {
          ^

TypeError: _.contains is not a function
    at C:\dev\code\tippy-app\hooks\after_plugin_add\register_plugins.js:12:11
    at arrayEach (C:\dev\code\tippy-app\node_modules\lodash\lodash.js:474:11)
    at Function.forEach (C:\dev\code\tippy-app\node_modules\lodash\lodash.js:7633:11)
    at Object.<anonymous> (C:\dev\code\tippy-app\hooks\after_plugin_add\register_plugins.js:11:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
 Error: Hook failed with error code 1: C:\dev\code\tippy-app\hooks\after_plugin_add\register_plugins.js

**Comment by dpa99c** [comment]
The error is occurring in `hooks\after_plugin_add\register_plugins.js` which looks to be some custom hook script in your project. It has nothing to do with this plugin. Looks to be caused by a reference to `_.contains` which is not an available method in [lodash 4.x](https://lodash.com/docs). Use [`_.includes`](https://lodash.com/docs#includes) instead.
