### ISSUE TITLE
installation with plugman hook issues

### ISSUE THREAD

**Issue by darewreck54** [dpa99c/cordova-custom-config#96]
I wanted to install this plugin specific to a platform and in this case android.  However, when i run the command:
`
plugman install --platform android --project ./platforms/android --plugin cordova-custom-config`

It installs it but throws out some error:

```
Failed to install 'cordova-custom-config':Error: Cannot find module '/cordova/plugins/cordova-custom-config/hooks/logger.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/cordova/platforms/android/cordova/plugins/cordova-custom-config/hooks/resolveDependencies.js:12:18)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/plugman/node_modules/q/q.js:816:30)
Cannot find module '/cordova/plugins/cordova-custom-config/hooks/logger.js'
```

When i use the normal Cordova cli, i don't experience this issue.  

I believe the plugin hooks are trying to locate the script based on the location structure of a cordova cli use case.  When you use plugman, it doesn't install the plugin in the top level /plugin directory, but installs under the /platform/android/.../plugin directory.  

I'm not really sure how to do this but somehow have to configure the paths in a way where it can find it relative to where it's installed.  

Not sure if this is an issue with the plugin or an issue with how plugman handles plugin hooks.  Also the method of copying all the hooks to the top level is being depreciated.

Thanks,
Derek

**Comment by dpa99c** [comment]
This plugin is intended to output custom platform configuration based on entries in the config.xml. Therefore, there it contains no native code so there's no reason to install the plugin via plugman for a specific platform. If you want to use it only for a specific platform, then just define config entries for that platform. I don't intend to make any changes to make it support platform-specific installation via plugman as I see no use case for this.
